Dremio jdbc plugin
kestra-io/plugin-jdbc pull request #162
Opened 2023-10-16 10:31 UTC by iNikitaGricenko

Added dreamio query task and Trigger using the JDBC drive.
Added Query task using the Arrow Flight SQL JDBC drive.
**(No test!)**

2023-10-20 10:09 UTC, loicmathieu requested changes
I don't think using both drivers is useful as you can do the same with the Dremio driver and the Apache Flight SQL driver.

We will discuss internally if we need to change something about that.

2023-10-20 10:09 UTC, loicmathieu commented on plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/ArrowFlightQuery.java
> +    title = "Query a Dremio database through Apache Arrow Flight sql driver."
```suggestion
    title = "Query a Dremio database through Apache Arrow Flight SQL."
```

2023-10-20 10:09 UTC, loicmathieu commented on plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/ArrowFlightQuery.java
> +            title = "Send a sql query to a Dremio direct database and fetch a row as outputs using Apache Arrow Flight sql driver",
```suggestion
            title = "Send a SQL query to a Dremio database and fetch a row as outputs using Apache Arrow Flight SQL",
```

2023-10-20 10:09 UTC, loicmathieu commented on plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/ArrowFlightQuery.java
> +            title = "Send a sql query to a Dremio coordinator and fetch a row as outputs using Apache Arrow Flight sql driver",
```suggestion
            title = "Send a SQL query to a Dremio coordinator and fetch a row as outputs using Apache Arrow Flight SQL",
```

2023-10-20 10:09 UTC, loicmathieu commented on plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/Query.java
> +            title = "Send a sql query to a Dremio database and fetch a row as outputs",
```suggestion
            title = "Send a SQL query to a Dremio database and fetch a row as outputs",
```

2023-10-20 10:09 UTC, loicmathieu commented on plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/Trigger.java
> +            title = "Wait for a sql query to return results and iterate through rows",
```suggestion
            title = "Wait for a SQL query to return results and iterate through rows",
```

2023-10-20 10:09 UTC, loicmathieu commented on plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/Trigger.java
> +                "    type: io.kestra.plugin.jdbc.clickhouse.Trigger",
```suggestion
                "    type: io.kestra.plugin.jdbc.dremio.Trigger",
```

2023-10-24 00:12 UTC, anna-geller commented
closes https://github.com/kestra-io/kestra/issues/1854

2023-10-24 10:01 UTC, closed without merging