Splited plugins Arrow flight And Dremio #1854 #162
kestra-io/plugin-jdbc pull request #169
Opened 2023-10-24 10:01 UTC by iNikitaGricenko

### What changes are being made and why?

Added Dremio jdbc plugin and Apache Arrow Flight. Splited both plugins as separated plugins
---

### How the changes have been QAed?
Trough Dremio test drive and Dremio account

```yaml
id : dremio-listen
namespace: dev

triggers:
  - id: watch
    type: io.kestra.plugin.jdbc.dremio.Trigger
    url: "jdbc:arrow-flight-sql://localhost:31010/?useEncryption=false"
    username: "dremio"
    password: "dremio123"
    sql: "SELECT * from \"dremio-test\".\"postgres.public\".departments"
    fetch: true
    interval: PT10S

tasks:
  - id: query
    type: io.kestra.plugin.jdbc.dremio.Query
    url: "jdbc:arrow-flight-sql://localhost:31010/?useEncryption=false"
    username: "dremio"
    password: "dremio123"
    sql: "SELECT * from \"dremio-test\".\"postgres.public\".departments"
    fetchOne: true
```
---

### Setup Instructions

- [Dremio Arrow Flight Authentication (URL example)](https://docs.dremio.com/current/sonar/client-applications/drivers/arrow-flight-sql-jdbc-driver/)

2023-10-24 12:44 UTC, loicmathieu requested changes
It is missing tests for Query and Trigger tasks.
In your test, please create a table with multiple row types (as done in other JDBC plugins) to check that the CellConverter didn't need to handle type conversions.

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-arrow-flight/build.gradle
> +project.description = 'Query Dremio databases using the Kestra Apache Arrow Flight JDBC plugin.'
```suggestion
project.description = 'Query a compatible database using the Kestra Apache Arrow Flight SQL JDBC plugin.'
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-arrow-flight/build.gradle
> +                "X-Kestra-Title": "Arrow Flight",
```suggestion
                "X-Kestra-Title": "Arrow Flight SQL",
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Query.java
> +    title = "Query a databases through Apache Arrow Flight SQL driver."
```suggestion
    title = "Query a database through Apache Arrow Flight SQL driver."
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Query.java
> +            title = "Send a sql query to a Dremio direct database and fetch a row as outputs using Apache Arrow Flight SQL driver",
```suggestion
            title = "Send a SQL query to a database and fetch a row as outputs using Apache Arrow Flight SQL driver",
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Query.java
> +                "sql: select * FROM \"postgres.public\".departments",
```suggestion
                "sql: select * FROM departments",
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/Trigger.java
> +            title = "Wait for a sql query to return results and iterate through rows",
```suggestion
            title = "Wait for a SQL query to return results and iterate through rows",
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-dremio/build.gradle
> +project.description = 'Query Dremio databases using the Kestra JDBC plugin.'
```suggestion
project.description = 'Query Dremio database using the Kestra JDBC plugin.'
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/Query.java
> +            title = "Send a sql query to a Dremio database and fetch a row as outputs",
```suggestion
            title = "Send a SQL query to a Dremio database and fetch a row as outputs",
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-dremio/src/main/java/io/kestra/plugin/jdbc/dremio/Trigger.java
> +            title = "Wait for a sql query to return results and iterate through rows",
```suggestion
            title = "Wait for a SQL query to return results and iterate through rows",
```

2023-10-24 12:44 UTC, loicmathieu commented on plugin-jdbc-arrow-flight/src/main/java/io/kestra/plugin/jdbc/arrowflight/package-info.java
> +    description = "This sub-group of plugins contains tasks for accessing the databases through Apache Arrow Flight.",
```suggestion
    description = "This sub-group of plugins contains tasks for accessing a databases through Apache Arrow Flight SQL.",
```

2023-10-25 20:32 UTC, anna-geller commented
@iNikitaGricenko using this branch, I'm getting a bunch of errors on kestra server startup. see below. could you cross-check?

```yaml
2023-10-25 22:28:14,507 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.postgresql.Batch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,509 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcQuery' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,509 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.postgresql.Trigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,509 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcBatch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,509 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.postgresql.Query' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,509 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.postgresql.CopyOut' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,509 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.postgresql.CopyIn' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,510 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.postgresql.AbstractCopy' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,510 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcTrigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-postgres-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,514 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.vertica.Trigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-vertica-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,515 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.vertica.Batch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-vertica-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,515 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcQuery' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-vertica-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,515 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcBatch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-vertica-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,515 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcTrigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-vertica-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,515 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.vertica.Query' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-vertica-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,622 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcQuery' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-clickhouse-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,622 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.clickhouse.Trigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-clickhouse-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,622 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcBatch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-clickhouse-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,623 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.clickhouse.Query' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-clickhouse-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,623 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcTrigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-clickhouse-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,625 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcQuery' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,625 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcBatch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,625 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcTrigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,647 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcQuery' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-arrow-flight-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,648 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcBatch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-arrow-flight-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,648 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.arrowflight.Trigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-arrow-flight-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,648 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.arrowflight.Query' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-arrow-flight-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,648 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcTrigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-arrow-flight-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,677 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.sqlserver.Trigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-sqlserver-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,677 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcQuery' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-sqlserver-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,677 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.sqlserver.Query' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-sqlserver-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,677 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcBatch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-sqlserver-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,677 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcTrigger' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-sqlserver-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,677 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.sqlserver.Batch' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-sqlserver-0.13.0-SNAPSHOT.jar'
2023-10-25 22:28:14,800 WARN  main         io.kestra.core.plugins.PluginScanner Unable to load class 'io.kestra.plugin.jdbc.AbstractJdbcQuery' on plugin 'file:/Users/anna/dev/plugins/plugin-jdbc-pinot-0.13. [...]

2023-10-26 06:58 UTC, iNikitaGricenko commented
@anna-geller, databases that are given into Dremio Test Drive does not support apache arrow flight

2023-10-26 13:14 UTC, anna-geller commented
I'm sorry, I didn't know that.

2023-10-26 13:15 UTC, merged